import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import About from './about'
import Contact from './contact'
import Blog from './blog'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>MyBlogSpace &hearts; &hearts;</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/fav.png" />
      </Head>
      <nav className={styles.nav}>
        <ul>
          <li><Link href="/">Home</Link></li>
          <li><Link href="/about">About</Link></li>
          <li><Link href="/blog">Blog</Link></li>
          <li><Link href="/contact">Contact</Link></li>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
          MyblogSpace
        </h1>
        <div className={styles.info} >
          Discover a world of ideas and inspiration in our engaging blog.
        </div>
        <div className='blog'>

          <h2>Popular Blog</h2>
          <div className={styles.center}>
            <div className="blogItem">
              <h3>How to learn the javascript</h3>
              <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aperiam obcaecati eveniet, doloribus eaque velit quis excepturi quasi eos consequuntur necessitatibus temporibus error in sapiente eligendi rerum? Id reprehenderit quisquam quos!</p>
            </div>

            <div className="blogItem">
              <h3>How to learn the javascript</h3>
              <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aperiam obcaecati eveniet, doloribus eaque velit quis excepturi quasi eos consequuntur necessitatibus temporibus error in sapiente eligendi rerum? Id reprehenderit quisquam quos!</p>
            </div>

            <div className="blogItem">
              <h3>How to learn the javascript</h3>
              <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aperiam obcaecati eveniet, doloribus eaque velit quis excepturi quasi eos consequuntur necessitatibus temporibus error in sapiente eligendi rerum? Id reprehenderit quisquam quos!</p>
            </div>

            <div className="blogItem">
              <h3>How to learn the javascript</h3>
              <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aperiam obcaecati eveniet, doloribus eaque velit quis excepturi quasi eos consequuntur necessitatibus temporibus error in sapiente eligendi rerum? Id reprehenderit quisquam quos!</p>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
